MVCceidec2016/Models/Gcontraseña.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MVCceidec2016.Models
{
    public class Gcontraseña : Password //hereda de password
    {
        //agrega la propiedad longitud
        [Required(ErrorMessage = "Se requiere que se de un número para los dígitos de la contraseña")]
        [DisplayName("Digitos:")]
        [Range(1, 128)]
        public int longitud { get; set; }

        //agrega la propiedad cnt
        [Required(ErrorMessage = "Se requiere que se de un número para la cantidad de caracteres no triviales")]
        [Range(0,100)]
        [DisplayName("Digitos Esp:")]
        public int cnt { get; set; }


        //agrega sobrecarga al método GenerarContraseña (recibe 2 enteros), no esta en la clase base (Password) sólo en esta.
        public static string GenerarContraseña(int l, int c)
        {
            return System.Web.Security.Membership.GeneratePassword(l, c);
        }
        public Gcontraseña()
        {
            //Se inicializan a 1 ya que para generar contraseña se requiere que la longitud y el cnt sea de "al menos" 1.
            longitud = 25;
           // cnt = 1;
            pwd = GenerarContraseña(longitud, cnt);
        }
    }
}

MVCceidec2016/Controllers/GcontraseñaController.cs
using System.Web.Mvc;
using MVCceidec2016.Models;

namespace MVCceidec2016.Controllers
{
    public class GcontraseñaController : Controller
    {
        // GET: Gcontraseña
        public ActionResult Index()
        {
            Gcontraseña gc = new Gcontraseña();
            return View(gc);
        }

        [HttpPost]
        public ActionResult Index(Gcontraseña gc)
        {
            if (! (gc.cnt > gc.longitud) ) //cnt no puede ser más grande que el tamaño de la contraseña
            {
                gc.pwd = Gcontraseña.GenerarContraseña(gc.longitud, gc.cnt);
                return View(gc);
            }
            //Si llegamos este lejos es porque cnt es más grande que el tamaño de la contraseña
            //creo el mensaje de error
            ViewBag.DetalleDelError = "La longitud de los caracteres especiales no puede ser mayor al numero de digitos de la contraseña";
            return View("Error");
        }

        public ActionResult ActualizarC(Gcontraseña gc)
        {
            if (!(gc.cnt > gc.longitud)) //cnt no puede ser más grande que el tamaño de la contraseña
            {
                gc.pwd = Gcontraseña.GenerarContraseña(gc.longitud, gc.cnt);
                return PartialView("_ActualizarC", gc);
            }
            ViewBag.DetalleDelError = "No se puede actualizar la contraseña, Function:Actualizar, Action: ActualizarC. <br /> La longitud de los caracteres especiales no puede ser mayor al numero de digitos de la contraseña";
            return View("Error");
        }
        
    }
}

MVCceidec2016/Views/Gcontraseña/Index.cshtml
@model MVCceidec2016.Models.Gcontraseña
@{
    ViewBag.Title = "Llamada Ajax + Partial View";
}

<h2>@ViewBag.Title</h2>


@*@using (Html.BeginForm("Index","Gcontraseña", FormMethod.Post))
{
    <div class="form-horizontal">
        @Html.DisplayNameFor(m => m.longitud) :  @Html.EditorFor(m => m.longitud) <br />
        @Html.DisplayNameFor(m => m.cnt) :  @Html.EditorFor(m => m.cnt) <br />
    </div>

    <div class="form-control">
        @Html.DisplayFor(m => m.pwd)
        
    </div>

    <input type="submit" />
}*@

@*                       accion        controlador                      *@
@using (Ajax.BeginForm("ActualizarC", "Gcontraseña", new AjaxOptions()
{
    HttpMethod = "POST",
    //LoadingElementId = "cambio",
    UpdateTargetId ="cambio",
    InsertionMode = InsertionMode.Replace
}))
{
    <div class="form-horizontal">
        
        @Html.DisplayNameFor(m => m.longitud) : @Html.EditorFor(m => m.longitud, new {@class="col-md-8 form-control"}) <br/>
        @Html.DisplayNameFor(m => m.cnt) : @Html.EditorFor(m => m.cnt) <br/>
    </div>

    <div class="form-control" id="cambio">
        @Html.DisplayFor(m => m.pwd)
    </div>
    <input type="submit" />

}

@section scripts{
    @Scripts.Render("~/bundles/jqueryval")
}

MVCceidec2016/Views/Gcontraseña/_ActualizarC.cshtml
@model MVCceidec2016.Models.Gcontraseña

    @Html.DisplayFor(m => m.pwd)